### ISSUE TITLE
"yarn test" coughs a hard error

### ISSUE THREAD

**Issue by MikeTheCanuck** [MikeTheCanuck/WhoDidITalkTo#104]
While adding my first additional unit test, I tried to verify that `yarn test` would work in my local environment and show this next test working.

Instead, it coughed hard - and even without the new test:

```
$ yarn test
yarn run v1.3.2
$ react-scripts test --env=jsdom
2017-12-05 12:42 node[28987] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-12-05 12:42 node[28987] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-12-05 12:42 node[28987] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1024:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1351:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Mikes-MacBook-Pro15:WhoDidITalkTo mike$ yarn test
yarn run v1.3.2
$ react-scripts test --env=jsdom
2017-12-05 12:43 node[29017] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-12-05 12:43 node[29017] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-12-05 12:43 node[29017] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1024:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1351:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MikeTheCanuck** [comment]
And apparently this is one solution that has worked for some (installing watchman tool):
https://github.com/facebookincubator/create-react-app/issues/871

In fact, that guidance has migrated to the [React Scripts README](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#troubleshooting), though it's implied rather than called out directly.

Once I ran `brew install watchman`, the next execution of `yarn test` worked like a charm.
